
TrajectoryPlannerROS:

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  sim_time: 1.0
  meter_scoring: true 
  occdist_scale: 0.02

  max_vel_x: 0.6
  min_vel_x: 0.1
  max_vel_theta: 1
  global_frame_id: 'odom'


  controller_frequency: 15.0