
map_type: costmap

obstacle_range: 5
raytrace_range: 6

transform_tolerance: 0.3

robot_radius: 0.5
inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /panos_bot/laser/scan, marking: true, clearing: true}
